apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eksdemo
  template:
    metadata:
      labels:
        app: eksdemo
    spec:
      containers:
        - name: back-end
          image: 368745844931.dkr.ecr.ap-south-1.amazonaws.com/testrepo:latest
          ports:
            - containerPort: 8080